### Créer un nouveau secret (Test POST)
POST http://localhost:8081/api/secrets
Content-Type: application/json

{
  "contentBlob": "U2VjcmV0IFRlc3Q=",
  "isFile": false,
  "senderEmail": "test@example.com"
}